borrow fee for ethereum
unitprotocol/core pull request #55
Opened 2021-11-08 20:08 UTC by pumpurum2

ported 
- changes related to borrow fee
- small refactoring in exit
- deploy scripts (adapted)
- tests

2021-11-09 15:25 UTC, Eenae requested changes

2021-11-09 15:25 UTC, Eenae commented on contracts/vault-managers/CDPManager_Fallback.sol
> +        vault.update(asset, msg.sender);
See above

2021-11-09 15:25 UTC, Eenae commented on hardhat.config.js
> +    .addOptionalParam('withHelpers', 'With helpers', true, types.boolean)
unused?

2021-11-11 08:44 UTC, Eenae approved these changes

2021-11-11 09:52 UTC, 34x4p08 approved these changes

2021-11-15 09:16 UTC, merged