events on admin action and removed unused code
unitprotocol/core pull request #63
Opened 2021-11-17 09:41 UTC by pumpurum2

2021-11-17 10:09 UTC, Eenae requested changes
"Just one more thing", can we move the events to interfaces? As a bonus, the contracts will finally inherit from their own interfaces.

2021-11-17 21:16 UTC, pumpurum2 commented
+ removed vaultParameters from all interfaces expect IVaultManagerParametes since they are unused
+ removed old col-related methods from IVault

2021-11-18 08:20 UTC, Eenae approved these changes

2021-11-18 08:20 UTC, Eenae commented on contracts/CollateralRegistry.sol
>  import "./VaultParameters.sol";
Here and below `VaultParameters` is no longer needed per se.

2021-11-19 09:50 UTC, merged